services:
  bot:
    image: leroideskiwis/omega-bot:latest
    volumes:
      - ./data/:/opt/omega-bot/data
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_CHANNEL_ID=${LOG_CHANNEL}
      - GROS_PUANT_ID=${GROS_PUANT_ID}
      - LIVRE_DARGENT_ID=${LIVRE_DARGENT_ID}
      - BOT_CHANNEL_ID=${BOT_CHANNEL_ID}